### ISSUE TITLE
Frontend rendering inconsistant.

### ISSUE THREAD

**Issue by natesales** [CGScheduleSquad/cgs-schedule#43]
There appears to be inconsistent behavior in rendering certain schedules.

The first 2 samples are on my brother's laptop, and the last (correct) example is on mine. Both machines are Dell XPS 13 9370 laptops at 3840×2160.

Here we have Firefox:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Firefox/70.0
![Screenshot (2)](https://user-images.githubusercontent.com/20391440/68267020-ba615980-0005-11ea-9304-b750bd7d370b.png)

And Chrome:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit (KHTML, like Gecko) Chrome/78
![Screenshot (3)](https://user-images.githubusercontent.com/20391440/68267041-d36a0a80-0005-11ea-8c23-5b3aadf9b243.png)

Then we have the expected behavior on one of my machines:
Mozilla/5.0 (X11; Linux x86_64;) Firefox/71
![image](https://user-images.githubusercontent.com/20391440/68267068-eed51580-0005-11ea-9416-b07d9c1a2faf.png)

Call me paranoid, but user agents versions are simplified. Let me know if more complete version information is required.

**Comment by liamjwang** [comment]
@nwsnate I'm pretty sure this is because the system time is set incorrectly on your brother's laptop, notice how the block start times are offset by two hours, so they are rendered as special schedules since they don't fit into the normal day time slots. I think our date parsing currently requires the system time to be set correctly but I'll look into changing that.

**Comment by liamjwang** [comment]
@nwsnate Please see if the issue is fixed after #49

**Comment by natesales** [comment]
Looks good. Thanks!
