### ISSUE TITLE
Links to haiku inconsistant

### ISSUE THREAD

**Issue by KazMalhotra** [CGScheduleSquad/cgs-schedule#54]
![image](https://user-images.githubusercontent.com/49257206/69249525-dc5cef00-0b62-11ea-8c34-9b7818fe8436.png)
Links to French, lunch and PE work, but English, science, and music do not. This is not because these classes do not have haiku pages.
Here is a video demonstrating this.
https://drive.google.com/file/d/1NcQuBPmncLGm4chauCOuEvcpK6hg9RNz/view?usp=sharing
sorry, OBS wasn't working so the video is a bit broken.

**Comment by liamjwang** [comment]
It looks like you entered "English 7 " (with the trailing space) into the spreadsheet instead of "English 7". 
Note that the spreadsheet said to enter _exact_ class names :)
I'll make it trim the spaces automatically sometime soon, but for now, you could just change the spreadsheet.
In the future, please also paste a link to your schedule where you are having issues.

**Comment by KazMalhotra** [comment]
Ok, thanks.
